### ISSUE TITLE
[Question] Access to the SVG files?

### ISSUE THREAD

**Issue by WalidChebaro** [CoderNamedHendrick/solar_icons#10]
Hey do you have access to the SVG files used to generate the font? And do you mind sharing them?

**Comment by CoderNamedHendrick** [comment]
Hello @WalidChebaro. You can find the icons [here](https://www.figma.com/file/HYNWFpkDBfGC8PDNbaXokq/Solar-Icons-Set-(Community)?type=design&mode=design&t=qOPVImbbCwYTEupb-0).

**Comment by WalidChebaro** [comment]
@CoderNamedHendrick Thank you but these ones brake when I convert them to a font

**Comment by CoderNamedHendrick** [comment]
Can you point me to what section of icons you're referring to @WalidChebaro?

**Comment by WalidChebaro** [comment]
@CoderNamedHendrick Broken set
