### ISSUE TITLE
Consolidate Icon Classes

### ISSUE THREAD

**Issue by JideGuru** [CoderNamedHendrick/solar_icons#4]
Instead of having `SolarIconsBold`, `SolarIconsBroken`, and `SolarIconsOutline` we can have just one class called `SolarIcons` and have icons named like `SolarIcons.forwardBold`, `SolarIcons.forwardBroken` and `SolarIcons.forwardOutline`

**Comment by CoderNamedHendrick** [comment]
Hmmm. Is there any significant benefit to doing this? The time and effort to do this would be high unless there's a considerable benefit to reimplementing it this way. It wouldn't feel worth it

**Comment by JideGuru** [comment]
I think you're right - it's not necessary. The major benefit of doing this is the ease of use.
